- name: nginx install and run
  hosts: web
  become: yes #take sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package: #To install packages
      name: nginx
      state: present
      
  - name: run nginx
    ansible.builtin.service: #To run the packages
      name: nginx
      state: started
      enabled: yes