- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false
  - name: TRAINER
    prompt: Please enter the trainer name
    private: false
  - name: DURATION
    prompt: Please enter the duration time
    private: false
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{TRAINER}}"
  