- name: devops course info
  hosts: local
  connection: local #for server no need to place user name & password
  vars:
    course: "DevOps with AWS"
    duration: 120
    topics:
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8
    live: true #boolean
    tools: #map/dictionary
      ci: Jenkins
      cm: Ansible
      cloud: AWS
      aws:
      - IAM
      - S3
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "hi, iam learning {{course}} with duraton {{duration}} topics are {{topics}} and live: {{live}}, tools are: {{tools}}"