- name: demo on filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"

  - name: convert to uppercase
    vars:
      greeting: "Hello ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

  - name: convert to lowercase
    vars:
      greeting: "Hello ramesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"

  - name: get unique values
    vars:
      numbers: [1,2,3,45,6,4,3,1]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"

  - name: get min and max values
    vars:
      numbers: [1,2,3,45,6,4,3,1]
    ansible.builtin.debug:
      msg: " min: {{ numbers | min }}, max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "devops with aws"
        duration: 120
        trainer: "siva"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
        - { "key": "name","value": "devops with aws" }
        - { "key": "duration","value": 120 }
        - { "key": "trainer","value": "siva" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"